//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakYonetim.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PMSEntities : DbContext
    {
        public PMSEntities()
            : base("name=PMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<t_adres> t_adres { get; set; }
        public virtual DbSet<t_contact> t_contact { get; set; }
        public virtual DbSet<t_contactDosyalari> t_contactDosyalari { get; set; }
        public virtual DbSet<t_iletisimIzinKayit> t_iletisimIzinKayit { get; set; }
        public virtual DbSet<t_iletisimIzinleri> t_iletisimIzinleri { get; set; }
        public virtual DbSet<t_iletisimStatusu> t_iletisimStatusu { get; set; }
        public virtual DbSet<t_kampanyalar> t_kampanyalar { get; set; }
        public virtual DbSet<t_kullanici> t_kullanici { get; set; }
        public virtual DbSet<t_lead> t_lead { get; set; }
        public virtual DbSet<t_mulkModul> t_mulkModul { get; set; }
        public virtual DbSet<t_mulkOzellik> t_mulkOzellik { get; set; }
        public virtual DbSet<t_mulkTipi> t_mulkTipi { get; set; }
        public virtual DbSet<t_mulkTipiModul> t_mulkTipiModul { get; set; }
        public virtual DbSet<t_mulkTipiOzellik> t_mulkTipiOzellik { get; set; }
        public virtual DbSet<t_ozellik> t_ozellik { get; set; }
        public virtual DbSet<t_roller> t_roller { get; set; }
        public virtual DbSet<t_rolTablosu> t_rolTablosu { get; set; }
        public virtual DbSet<t_satisTipi> t_satisTipi { get; set; }
        public virtual DbSet<t_tercihEdilenIletisim> t_tercihEdilenIletisim { get; set; }
        public virtual DbSet<t_uyrukUlke> t_uyrukUlke { get; set; }
        public virtual DbSet<t_yetkiGrubu> t_yetkiGrubu { get; set; }
        public virtual DbSet<t_mulk> t_mulk { get; set; }
        public virtual DbSet<t_modul> t_modul { get; set; }
        public virtual DbSet<t_mulkIMGs> t_mulkIMGs { get; set; }
        public virtual DbSet<t_satisTipiModul> t_satisTipiModul { get; set; }
        public virtual DbSet<t_mulkAdres> t_mulkAdres { get; set; }
    }
}
