//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakYonetim.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_lead
    {
        public int id { get; set; }
        public int contactID { get; set; }
        public int iletisimStatusuID { get; set; }
        public int mulkSahibi { get; set; }
        public System.DateTime sorguTarihi { get; set; }
        public System.DateTime gelecekRandevu { get; set; }
        public int sourceDetayID { get; set; }
        public int mulkTipiID { get; set; }
    }
}
