//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakYonetim.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_mulkModul
    {
        public int id { get; set; }
        public int mulkID { get; set; }
        public Nullable<int> modulID { get; set; }
        public string deger { get; set; }
    
        public virtual t_mulk t_mulk { get; set; }
        public virtual t_modul t_modul { get; set; }
    }
}
